steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['buildUberJar']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/leto:latest', '.']
    timeout: 600s
images: ['gcr.io/$PROJECT_ID/leto-app:latest']